name: Sample (uses-2)
on:
  push:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: tmm1/gha-repro-self-referential/.github/workflows/bootstrap@main
        with:
          msg: foo