name: Sample (gh)
on:
  push:

jobs:
  sample:
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
      - name: Bootstrap
        working-directory: .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          action=.github/workflows/bootstrap/action.yml
          mkdir -p $(dirname $action)
          gh api -H "Accept: application/vnd.github.v3.raw" \
            "repos/${{ github.repository }}/contents/$action?ref=${{ github.sha }}" > $action

      - uses: ./.github/workflows/bootstrap
        with:
          msg: foo

      - name: Get job name
        run: |
          set -x
          echo "Job name is $GITHUB_JOB"
          echo "Job ID is ${{ github.job }}"
          echo "How about ${{ toJSON(github.jobs) }}"
